# Read Census data csv received on 06/23/23, analyze and load into Postgres Database

Sudha Kumar
07/06/23

For 1379 - Make Census data available for API Views

In [3]:
#pip install jupyter_contrib_nbextensions && jupyter contrib nbextension install

In [4]:
#!jupyter nbextension enable --py widgetsnbextension

In [5]:
pip install psycopg2-binary

Requirement already satisfied: psycopg2-binary in /opt/homebrew/lib/python3.10/site-packages (2.9.6)

[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: /opt/homebrew/opt/python@3.10/bin/python3.10 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [6]:
pip install sqlalchemy

Requirement already satisfied: sqlalchemy in /opt/homebrew/lib/python3.10/site-packages (2.0.18)
Requirement already satisfied: typing-extensions>=4.2.0 in /opt/homebrew/lib/python3.10/site-packages (from sqlalchemy) (4.4.0)

[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: /opt/homebrew/opt/python@3.10/bin/python3.10 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

## Import Libraries

In [7]:
import pandas as pd
import psycopg2
from sqlalchemy import create_engine

## Load data

In [8]:
df = pd.read_csv("/Users/sudhakumar/Documents/Census_data/Data_0623/csv_files/DISSEMINATION-CFDA_AGENCIES-EXPORT.csv")

In [9]:
df.head(10)

,AGENCYNUM,AGENCYNAME,I_9,III_9,III_10A
0,1,African Development Foundation,S,S,P
1,2,Agency for International Development,P,P,P
2,10,Department of Agriculture,P,P,P
3,23,Appalachian Regional Commission,S,P,P
4,88,Architectural & Transportation Barriers Compli...,S,S,P
5,13,Central Intelligence Agency,S,S,P
6,11,Department of Commerce,P,P,P
7,29,Commission on Civil Rights,S,S,P
8,78,Commodity Futures Trading Commission,S,S,P
9,87,Consumer Product Safety Commission,S,S,P

In [10]:
df.tail(10)

    AGENCYNUM                            AGENCYNAME  I_9 III_9 III_10A
62         20          Department of Transportation    P     P       P
63         21                Department of Treasury    S     P       P
64         82      United States Information Agency    S     P       P
65         91      United States Institute of Peace    S     S       P
66         64        Department of Veterans Affairs    S     P       P
67         99                         Miscellaneous    S     P       P
68          0                                  None  NaN     P     NaN
69         72                                   NaN  NaN   NaN       P
70         97       Department of Homeland Security    S     P       P
71         98  Agency For International Development    P     P       P

## Size of data

In [11]:
df.shape

(72, 5)

## Columns in data

In [12]:
df.columns

Index(['AGENCYNUM', 'AGENCYNAME', 'I_9', 'III_9', 'III_10A'], dtype='object')

## Check data types

In [13]:
df.dtypes

AGENCYNUM      int64
AGENCYNAME    object
I_9           object
III_9         object
III_10A       object
dtype: object

## Check for null values

In [14]:
df.count()

AGENCYNUM     72
AGENCYNAME    71
I_9           69
III_9         70
III_10A       71
dtype: int64

## Statistics of Integer columns

In [15]:
#df.describe()

## Process data if needed

## Connect to Postgres database

In [16]:
url = "postgresql://postgres:1234@localhost:5432/postgres"

connection = psycopg2.connect(url)
connection.autocommit = True
cursor = connection.cursor()

cursor.execute("SELECT version();")
version = cursor.fetchone()
print(version)

('PostgreSQL 12.15 (Debian 12.15-1.pgdg120+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit',)

## Create table in Postgres database

In [17]:
# drop table if it already exists
cursor.execute('drop table if exists suk_cfda_agencies')
  
sql = '''CREATE TABLE suk_cfda_agencies(AGENCYNUM int,AGENCYNAME char(512),I_9 char(8), III_9 char(8), III_10A char(8));'''
cursor.execute(sql)

connection.close()

## Update table in Postgres database

In [18]:
url = "postgresql://postgres:1234@localhost:5432/postgres"
engine = create_engine(url)
df.to_sql('suk_cfda_agencies', con=engine, if_exists= 'replace')

72

In [19]:
url = "postgresql://postgres:1234@localhost:5432/postgres"

connection = psycopg2.connect(url)
connection.autocommit = True
cursor = connection.cursor()
# fetching all rows
sql1='''select * from suk_cfda_agencies;'''
cursor.execute(sql1)
for i in cursor.fetchall():
    print(i)
connection.close()

(0, 1, 'African Development Foundation', 'S', 'S', 'P')
(1, 2, 'Agency for International Development', 'P', 'P', 'P')
(2, 10, 'Department of Agriculture', 'P', 'P', 'P')
(3, 23, 'Appalachian Regional Commission', 'S', 'P', 'P')
(4, 88, 'Architectural & Transportation Barriers Compliance Board', 'S', 'S', 'P')
(5, 13, 'Central Intelligence Agency', 'S', 'S', 'P')
(6, 11, 'Department of Commerce', 'P', 'P', 'P')
(7, 29, 'Commission on Civil Rights', 'S', 'S', 'P')
(8, 78, 'Commodity Futures Trading Commission', 'S', 'S', 'P')
(9, 87, 'Consumer Product Safety Commission', 'S', 'S', 'P')
(10, 94, 'Corporation for National & Community Service', 'S', 'P', 'P')
(11, 90, 'Denali Commission', 'S', 'S', 'P')
(12, 12, 'Department of Defense', 'P', 'P', 'P')
(13, 84, 'Department of Education', 'P', 'P', 'P')
(14, 81, 'Department of Energy', 'P', 'P', 'P')
(15, 66, 'Environmental Protection Agency', 'P', 'P', 'P')
(16, 30, 'Equal Employment Opportunity Commission', 'S', 'S', 'P')
(17, 32, 'Federal Communications Commission', 'S', 'S', 'P')
(18, 83, 'Federal Emergency Management Agency', 'P', 'P', 'P')
(19, 33, 'Federal Maritime Commission', 'S', 'S', 'P')
(20, 34, 'Federal Mediation and Conciliation Service', 'S', 'S', 'P')
(21, 18, 'Federal Reserve System', 'S', 'S', 'P')
(22, 36, 'Federal Trade Commission', 'S', 'S', 'P')
(23, 39, 'General Services Administration', 'S', 'P', 'P')
(24, 40, 'Government Printing Office', 'S', 'S', 'P')
(25, 93, 'Department of Health and Human Services', 'P', 'P', 'P')
(26, 14, 'Department of Housing and Urban Development', 'P', 'P', 'P')
(27, 3, 'Institute for Museum Services', 'S', 'P', 'P')
(28, 4, 'Inter-American Foundation', 'S', 'S', 'P')
(29, 15, 'Department of the Interior', 'P', 'P', 'P')
(30, 61, 'International Trade Commission', 'S', 'S', 'P')
(31, 41, 'Interstate Commerce Commission', 'S', 'S', 'P')
(32, 16, 'Department of Justice', 'P', 'P', 'P')
(33, 17, 'Department of Labor', 'P', 'P', 'P')
(34, 9, 'Legal Services Corporation', 'S', 'P', 'P')
(35, 42, 'Library of Congress', 'S', 'S', 'P')
(36, 43, 'National Aeronautics & Space Administration', 'S', 'P', 'P')
(37, 89, 'National Archives & Records Administration', 'S', 'P', 'P')
(38, 92, 'National Council on Disability', 'S', 'S', 'P')
(39, 44, 'National Credit Union Administration', 'S', 'S', 'P')
(40, 5, 'National Endowment for the Arts', 'S', 'P', 'P')
(41, 6, 'National Endowment for the Humanities', 'S', 'P', 'P')
(42, 45, 'National Foundation on the Arts and Humanities', None, None, 'P')
(43, 68, 'National Gallery of Art', 'S', 'S', 'P')
(44, 46, 'National Labor Relations Board', 'S', 'S', 'P')
(45, 47, 'National Science Foundation', 'P', 'P', 'P')
(46, 77, 'Nuclear Regulatory Commission', 'S', 'S', 'P')
(47, 7, 'Office of National Drug Control Policy', 'S', 'P', 'P')
(48, 27, 'Office of Personnel Management', 'S', 'S', 'P')
(49, 70, 'Overseas Private Investment Corporation', 'S', 'S', 'P')
(50, 8, 'Peace Corps', 'S', 'S', 'P')
(51, 86, 'Pension Benefit Guaranty Corporation', 'S', 'S', 'P')
(52, 22, 'Postal Service', 'S', 'S', 'P')
(53, 53, "President's Committee on Employment of Persons with Disabilities", 'S', 'S', 'P')
(54, 57, 'Railroad Retirement Board', 'S', 'S', 'P')
(55, 85, 'Scholarship & Fellowship Foundations', 'S', 'S', 'P')
(56, 58, 'Securities and Exchange Commission', 'S', 'S', 'P')
(57, 59, 'Small Business Administration', 'S', 'P', 'P')
(58, 60, 'Smithsonian Institution', 'S', 'S', 'P')
(59, 96, 'Social Security Administration', 'S', 'P', 'P')
(60, 19, 'Department of State', 'S', 'P', 'P')
(61, 62, 'Tennessee Valley Authority', 'S', 'S', 'P')
(62, 20, 'Department of Transportation', 'P', 'P', 'P')
(63, 21, 'Department of Treasury', 'S', 'P', 'P')
(64, 82, 'United States Information Agency', 'S', 'P', 'P')
(65, 91, 'United States Institute of Peace', 'S', 'S', 'P')
(66, 64, 'Department of Veterans Affairs', 'S', 'P', 'P')
(67, 99, 'Miscellaneous', 'S', 'P', 'P')
(68, 0, 'None', None, 'P', None)
(69, 72, None, None, None, 'P')
(70, 97, 'Department of Homeland Security', 'S', 'P', 'P')
(71, 98, 'Agency For International Development', 'P', 'P', 'P')